source ~/.dotfiles/bashrc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/chikasawa/Downloads/google-cloud-sdk/path.bash.inc' ]; then source '/Users/chikasawa/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/chikasawa/Downloads/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/chikasawa/Downloads/google-cloud-sdk/completion.bash.inc'; fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH"
